### ISSUE TITLE
想知道关于vbot的后续

### ISSUE THREAD

**Issue by xmsz** [nbwsc/blog#2]
目前有项目也需要接入微信机器人
在逛了一圈以后，还是很担心被封号

我从https://blog.chatie.io/talk-about-wechat-robot/这里看到了3种方式
目前我更倾向于puppeteer

请问您现在使用的哪种方式

**Comment by nbwsc** [comment]
@xmsz 关于微信机器人后续我也没有更多的研究，前几个月网页版拉人进群的接口也被封了。我觉得网页版的能力肯定是越来越弱的，所以要正经做的话还是逆向 android 或者桌面客户端。当然如果你的需求比较简单，也可以用puppeteer和很快搞一个出来。

**Comment by xmsz** [comment]
好的 谢谢
